### ISSUE TITLE
ERROR TypeError: Cannot read property 'job' of undefined

### ISSUE THREAD

**Issue by dje4om** [opentable/hubot-rundeck#5]
Hi, 

i can list projects from rundeck with ```<mybot> rundeck projects <myalias>```
but, when i try to list jobs for a project : ```<mybot> rundeck '<MYPROJECT>' jobs <myalias>```, i get this error : 

```
ubot_1       |     at /home/hubot/node_modules/hubot-rundeck/src/rundeck.coffee:95:7
hubot_1       |     at /home/hubot/node_modules/hubot-rundeck/src/rundeck.coffee:66:11
hubot_1       |     at Parser.<anonymous> (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/lib/xml2js.js:489:18)
hubot_1       |     at emitOne (events.js:77:13)
hubot_1       |     at Parser.emit (events.js:169:7)
hubot_1       |     at Object.onclosetag (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/lib/xml2js.js:447:26)
hubot_1       |     at emit (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/node_modules/sax/lib/sax.js:624:35)
hubot_1       |     at emitNode (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/node_modules/sax/lib/sax.js:629:5)
hubot_1       |     at closeTag (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/node_modules/sax/lib/sax.js:889:7)
hubot_1       |     at Object.write (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/node_modules/sax/lib/sax.js:1436:13)
hubot_1       |     at Parser.exports.Parser.Parser.parseString (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/lib/xml2js.js:508:31)
hubot_1       |     at Parser.parseString (/home/hubot/node_modules/hubot-rundeck/node_modules/xml2js/lib/xml2js.js:7:59)
hubot_1       |     at /home/hubot/node_modules/hubot-rundeck/src/rundeck.coffee:65:16
hubot_1       |     at IncomingMessage.<anonymous> (/home/hubot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
hubot_1       |     at emitNone (events.js:72:20)
hubot_1       |     at IncomingMessage.emit (events.js:166:7)
hubot_1       |     at endReadableNT (_stream_readable.js:923:12)
hubot_1       |     at nextTickCallbackWith2Args (node.js:511:9)
hubot_1       |     at process._tickCallback (node.js:425:17)
```

it seems to be related to coffee script version

**Comment by senorcinco** [comment]
It might only apply to my version of Rundeck (2.6.9), but I found an [issue](https://github.com/rundeck/rundeck/issues/2009) on Rundeck's Github that ultimately solved this for me.  

I removed the "Content-Type" header and then the jobs were returned correctly.

```
class Rundeck
  constructor: (@robot, @url, @authToken) ->
    @logger = @robot.logger

    @baseUrl = "#{@url}/api/17"

    @headers =
      "Accept": "application/xml"
      "X-Rundeck-Auth-Token": "#{@authToken}"

    @plainTextHeaders =
      "Accept": "text/plain"
      "Content-Type": "text/plain"
      "X-Rundeck-Auth-Token": "#{@authToken}"
```
